name: Telegram Handler

on:
  push:
    tags: ["v*.*.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/telegram-handler
  IMAGE_NAME_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/telegram-handler

jobs:
  Python:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  Scan:
    name: Scan Docker image
    needs:
      - Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - id: dockerhub-image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.IMAGE_NAME_DOCKERHUB }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get version
        run: echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t test --build-arg DATE_CREATED=${{ steps.date.outputs.date }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: test
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

  Github-Registry:
    name: Github Registry
    needs:
      - Python
      - Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get version
        run: echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - id: github-image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build image
        run: >
          docker build
          -t ${{ steps.github-image.outputs.lowercase }}:${{ env.APP_VERSION }}
          -t ${{ steps.github-image.outputs.lowercase }}:latest
          --build-arg DATE_CREATED=${{ steps.date.outputs.date }}
          --build-arg VERSION=${{ env.APP_VERSION }}
          .

      - name: Log into registry Github
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Github
        run: docker push ${{ steps.github-image.outputs.lowercase }}

  Dockerhub-Registry:
    name: Dockerhub Registry
    needs:
      - Python
      - Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get version
        run: echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - id: dockerhub-image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.IMAGE_NAME_DOCKERHUB }}

      - name: Build image
        run: >
          docker build
          -t ${{ steps.dockerhub-image.outputs.lowercase }}:${{ env.APP_VERSION }}
          -t ${{ steps.dockerhub-image.outputs.lowercase }}:latest
          --build-arg DATE_CREATED=${{ steps.date.outputs.date }}
          --build-arg VERSION=${{ env.APP_VERSION }}
          .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{ steps.dockerhub-image.outputs.lowercase }}
